/*
 * Copyright 2022-2023 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 0.14.14
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"
#include "fsl_gpio.h"
#include "board.h"


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P0, pin_signal: PIO1_8/WUU0_IN10/LPTMR1_ALT3/TRACE_DATA0/FC4_P0/FC5_P4/CT_INP8/SCT0_OUT2/FLEXIO0_D16/PLU_OUT0/ENET0_TXD2/I3C1_SDA/TSI0_CH17/ADC1_A8,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, pull_value: low, input_buffer: enable,
    invert_input: normal}
  - {pin_num: B1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P1, pin_signal: PIO1_9/TRACE_DATA1/FC4_P1/FC5_P5/CT_INP9/SCT0_OUT3/FLEXIO0_D17/PLU_OUT1/ENET0_TXD3/I3C1_SCL/TSI0_CH18/ADC1_A9,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
	/* Enables the clock for PORT1: Enables clock */
	CLOCK_EnableClock(kCLOCK_Port0);
	CLOCK_EnableClock(kCLOCK_Port1);
	CLOCK_EnableClock(kCLOCK_Port2);
	CLOCK_EnableClock(kCLOCK_Port3);

	BOARD_InitGPIO();
	// BOARD_InitPWM();
	BOARD_InitUART();
	// BOARD_InitSPI();
	BOARD_InitCAN();
	// BOARD_InitIIC();
	BOARD_InitADC();
	BOARD_InitDAC();
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitGPIO
 * Description   : Configures pin routing for GPIO
 *
 * END ****************************************************************************************************************/
void BOARD_InitGPIO(void)
{
	 /* enable clock for GPIO*/
	CLOCK_EnableClock(kCLOCK_Gpio0);
	CLOCK_EnableClock(kCLOCK_Gpio1);
	CLOCK_EnableClock(kCLOCK_Gpio2);
	CLOCK_EnableClock(kCLOCK_Gpio3);

	const port_pin_config_t port_INPUT_config = {/* Internal pull-up/down resistor is disabled */
                                                      kPORT_PullDisable,
                                                      /* Low internal pull resistor value is selected. */
                                                      kPORT_LowPullResistor,
                                                      /* Fast slew rate is configured */
                                                      kPORT_FastSlewRate,
                                                      /* Passive input filter is disabled */
                                                      kPORT_PassiveFilterDisable,
                                                      /* Open drain output is disabled */
                                                      kPORT_OpenDrainDisable,
                                                      /* Low drive strength is configured */
                                                      kPORT_LowDriveStrength,
                                                      /* Pin is configured as PIO0_10 */
                                                      kPORT_MuxAlt0,
                                                      /* Digital input enabled */
                                                      kPORT_InputBufferEnable,
                                                      /* Digital input is not inverted */
                                                      kPORT_InputNormal,
                                                      /* Pin Control Register fields [15:0] are not locked */
                                                      kPORT_UnlockRegister};

	/* PORT0_10 (pin B12) is configured as PIO0_10 */
    PORT_SetPinConfig(PORT0, 8U, &port_INPUT_config);
	PORT_SetPinConfig(PORT0, 9U, &port_INPUT_config);
	PORT_SetPinConfig(PORT0, 2U, &port_INPUT_config);
	PORT_SetPinConfig(PORT0, 3U, &port_INPUT_config);
	PORT_SetPinConfig(PORT0, 4U, &port_INPUT_config);
	PORT_SetPinConfig(PORT2, 8U, &port_INPUT_config);
	PORT_SetPinConfig(PORT2, 9U, &port_INPUT_config);
	PORT_SetPinConfig(PORT2, 10U, &port_INPUT_config);

    /* Define the init structure for the input switch pin */
    gpio_pin_config_t sw_config = {
        kGPIO_DigitalInput,
        0,
    };

	GPIO_SetPinInterruptConfig(BOARD_SW_GPIO, BOARD_SW_GPIO_PIN, kGPIO_InterruptFallingEdge);
	EnableIRQ(BOARD_SW_IRQ);
	GPIO_PinInit(BOARD_SW_GPIO, BOARD_SW_GPIO_PIN, &sw_config);

	GPIO_PinInit(PFC1_FLT_GPIO, PFC1_FLT_GPIO_PIN, &sw_config);
	GPIO_PinInit(PFC2_FLT_GPIO, PFC2_FLT_GPIO_PIN, &sw_config);
	GPIO_PinInit(SYS_CFG0_GPIO, SYS_CFG0_GPIO_PIN, &sw_config);
	GPIO_PinInit(SYS_CFG1_GPIO, SYS_CFG1_GPIO_PIN, &sw_config);
	GPIO_PinInit(SYS_CFG2_GPIO, SYS_CFG2_GPIO_PIN, &sw_config);

	GPIO_PinInit(PWM1_FB_GPIO, PWM1_FB_GPIO_PIN, &sw_config);
	GPIO_PinInit(PWM2_FB_GPIO, PWM2_FB_GPIO_PIN, &sw_config);
	GPIO_PinInit(PWM3_FB_GPIO, PWM3_FB_GPIO_PIN, &sw_config);





	/* Define the init structure for the output LED pin*/
	gpio_pin_config_t gpio_config = {
		kGPIO_DigitalOutput,
		0,
	};

	/* Init output LED GPIO. */
	GPIO_PinInit(SS_RLY_EN_GPIO, SS_RLY_EN_GPIO_PIN, &gpio_config);

	/* Init output PFC1_EN GPIO. */
	GPIO_PinInit(PFC1_EN_GPIO, PFC1_EN_GPIO_PIN, &gpio_config);

	/* Init output PFC2_EN GPIO. */
	GPIO_PinInit(PFC2_EN_GPIO, PFC2_EN_GPIO_PIN, &gpio_config);

	/* Init output DCDC1_EN GPIO. */
	GPIO_PinInit(DCDC1_EN_GPIO, DCDC1_EN_GPIO_PIN, &gpio_config);

	/* Init output DCDC2_EN GPIO. */
	GPIO_PinInit(DCDC2_EN_GPIO, DCDC2_EN_GPIO_PIN, &gpio_config);

	/* Init output LED GPIO. */
    GPIO_PinInit(BOARD_LED_GPIO, BOARD_LED_GPIO_PIN, &gpio_config);
	GPIO_PinInit(DBG_LED_GPIO, DBG_LED0_PIN, &gpio_config);
	GPIO_PinInit(DBG_LED_GPIO, DBG_LED1_PIN, &gpio_config);
	GPIO_PinInit(DBG_LED_GPIO, DBG_LED2_PIN, &gpio_config);
	GPIO_PinInit(CAN_LED_GPIO, CAN_LED_RUN_PIN, &gpio_config);
	GPIO_PinInit(CAN_LED_GPIO, CAN_LED_ERROR_PIN, &gpio_config);

	/* Init LCD pin. */
	GPIO_PinInit(BOARD_LCD_CS_GPIO, BOARD_LCD_CS_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_RESET_GPIO, BOARD_LCD_RESET_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_RS_GPIO, BOARD_LCD_RS_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_SDA_GPIO, BOARD_LCD_SDA_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_SCL_GPIO, BOARD_LCD_SCL_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_ROM_IN_GPIO, BOARD_LCD_ROM_IN_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_ROM_OUT_GPIO, BOARD_LCD_ROM_OUT_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_ROM_SCK_GPIO, BOARD_LCD_ROM_SCK_GPIO_PIN, &gpio_config);
	GPIO_PinInit(BOARD_LCD_ROM_CS_GPIO, BOARD_LCD_ROM_CS_GPIO_PIN, &gpio_config);

	/* Init output PWM GPIO. */
	GPIO_PinInit(PWM1_GPIO, PWM1_GPIO_PIN, &gpio_config);
	GPIO_PinInit(PWM2_GPIO, PWM2_GPIO_PIN, &gpio_config);
	GPIO_PinInit(PWM3_GPIO, PWM3_GPIO_PIN, &gpio_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUART
 * Description   : Configures pin routing for UART
 *
 * END ****************************************************************************************************************/
void BOARD_InitUART(void)
{


	const port_pin_config_t port1_8_pinA1_config = {/* Internal pull-up/down resistor is disabled */
													kPORT_PullDisable,
													/* Low internal pull resistor value is selected. */
													kPORT_LowPullResistor,
													/* Fast slew rate is configured */
													kPORT_FastSlewRate,
													/* Passive input filter is disabled */
													kPORT_PassiveFilterDisable,
													/* Open drain output is disabled */
													kPORT_OpenDrainDisable,
													/* Low drive strength is configured */
													kPORT_LowDriveStrength,
													/* Pin is configured as FC4_P0 */
													kPORT_MuxAlt2,
													/* Digital input enabled */
													kPORT_InputBufferEnable,
													/* Digital input is not inverted */
													kPORT_InputNormal,
													/* Pin Control Register fields [15:0] are not locked */
													kPORT_UnlockRegister};
	/* PORT1_8 (pin A1) is configured as FC4_P0 */
	PORT_SetPinConfig(PORT1, 8U, &port1_8_pinA1_config);

	const port_pin_config_t port1_9_pinB1_config = {/* Internal pull-up/down resistor is disabled */
													kPORT_PullDisable,
													/* Low internal pull resistor value is selected. */
													kPORT_LowPullResistor,
													/* Fast slew rate is configured */
													kPORT_FastSlewRate,
													/* Passive input filter is disabled */
													kPORT_PassiveFilterDisable,
													/* Open drain output is disabled */
													kPORT_OpenDrainDisable,
													/* Low drive strength is configured */
													kPORT_LowDriveStrength,
													/* Pin is configured as FC4_P1 */
													kPORT_MuxAlt2,
													/* Digital input enabled */
													kPORT_InputBufferEnable,
													/* Digital input is not inverted */
													kPORT_InputNormal,
													/* Pin Control Register fields [15:0] are not locked */
													kPORT_UnlockRegister};
	/* PORT1_9 (pin B1) is configured as FC4_P1 */
	PORT_SetPinConfig(PORT1, 9U, &port1_9_pinB1_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSPI
 * Description   : Configures pin routing for SPI
 *
 * END ****************************************************************************************************************/
// void BOARD_InitSPI(void)
// {

// }

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitIIC
 * Description   : Configures pin routing for IIC
 *
 * END ****************************************************************************************************************/
// void BOARD_InitIIC(void)
// {

// }

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCAN
 * Description   : Configures pin routing for CAN
 *
 * END ****************************************************************************************************************/
void BOARD_InitCAN(void)
{
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);
	const port_pin_config_t port1_10_pinC3_config = {/* Internal pull-up/down resistor is disabled */
														 kPORT_PullDisable,
														 /* Low internal pull resistor value is selected. */
														 kPORT_LowPullResistor,
														 /* Fast slew rate is configured */
														 kPORT_FastSlewRate,
														 /* Passive input filter is disabled */
														 kPORT_PassiveFilterDisable,
														 /* Open drain output is disabled */
														 kPORT_OpenDrainDisable,
														 /* Low drive strength is configured */
														 kPORT_LowDriveStrength,
														 /* Pin is configured as CAN0_TXD */
														 kPORT_MuxAlt11,
														 /* Digital input enabled */
														 kPORT_InputBufferEnable,
														 /* Digital input is not inverted */
														 kPORT_InputNormal,
														 /* Pin Control Register fields [15:0] are not locked */
														 kPORT_UnlockRegister};
		/* PORT1_10 (pin C3) is configured as CAN0_TXD */
		PORT_SetPinConfig(PORT1, 10U, &port1_10_pinC3_config);

		const port_pin_config_t port1_11_pinD3_config = {/* Internal pull-up/down resistor is disabled */
														 kPORT_PullDisable,
														 /* Low internal pull resistor value is selected. */
														 kPORT_LowPullResistor,
														 /* Fast slew rate is configured */
														 kPORT_FastSlewRate,
														 /* Passive input filter is disabled */
														 kPORT_PassiveFilterDisable,
														 /* Open drain output is disabled */
														 kPORT_OpenDrainDisable,
														 /* Low drive strength is configured */
														 kPORT_LowDriveStrength,
														 /* Pin is configured as CAN0_RXD */
														 kPORT_MuxAlt11,
														 /* Digital input enabled */
														 kPORT_InputBufferEnable,
														 /* Digital input is not inverted */
														 kPORT_InputNormal,
														 /* Pin Control Register fields [15:0] are not locked */
														 kPORT_UnlockRegister};
		/* PORT1_11 (pin D3) is configured as CAN0_RXD */
		PORT_SetPinConfig(PORT1, 11U, &port1_11_pinD3_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUART
 * Description   : Configures pin routing for UART
 *
 * END ****************************************************************************************************************/
void BOARD_InitADC(void){
	/* Enables the clock for PORT4: Enables clock */
	CLOCK_EnableClock(kCLOCK_Port4);

	const port_pin_config_t port_ADC_config = {/* Internal pull-up/down resistor is disabled */
												  kPORT_PullDisable,
												  /* Low internal pull resistor value is selected. */
												  kPORT_LowPullResistor,
												  /* Fast slew rate is configured */
												  kPORT_FastSlewRate,
												  /* Passive input filter is disabled */
												  kPORT_PassiveFilterDisable,
												  /* Open drain output is disabled */
												  kPORT_OpenDrainDisable,
												  /* Low drive strength is configured */
												  kPORT_LowDriveStrength,
												  /* Pin is configured as ADC0_A2 */
												  kPORT_MuxAlt0,
												  /* Digital input disabled; it is required for analog functions */
												  kPORT_InputBufferDisable,
												  /* Digital input is not inverted */
												  kPORT_InputNormal,
												  /* Pin Control Register fields [15:0] are not locked */
												  kPORT_UnlockRegister};
	/* PORT4_16 (pin R8) is configured as ADC0_A6 */
	PORT_SetPinConfig(PORT4, 16U, &port_ADC_config);

	/* PORT4_17 (pin R9) is configured as ADC0_B6 */
	PORT_SetPinConfig(PORT4, 17U, &port_ADC_config);

	/* PORT4_19 (pin R10) is configured as ADC0_B1 */
	PORT_SetPinConfig(PORT4, 19U, &port_ADC_config);

	/* PORT4_13 (pin T7) is configured as ADC0_B5 */
	PORT_SetPinConfig(PORT4, 13U, &port_ADC_config);

	/* PORT4_20 (pin T10) is configured as ADC1_A6 */
	PORT_SetPinConfig(PORT4, 20U, &port_ADC_config);

	/* PORT4_13 (pin T7) is configured as ADC1_B5 */
	PORT_SetPinConfig(PORT4, 13U, &port_ADC_config);

	/* PORT5_0 (pin U16) is configured as ADC1_B8 */
	PORT_SetPinConfig(PORT5, 0U, &port_ADC_config);

	/* PORT5_1 (pin U17) is configured as ADC1_B9 */
	PORT_SetPinConfig(PORT5, 1U, &port_ADC_config);

	/* PORT5_2 (pin M10) is configured as ADC1_B10 */
	PORT_SetPinConfig(PORT5, 2U, &port_ADC_config);

	/* PORT5_3 (pin M11) is configured as ADC1_B11 */
	PORT_SetPinConfig(PORT5, 3U, &port_ADC_config);

}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUART
 * Description   : Configures pin routing for UART
 *
 * END ****************************************************************************************************************/
void BOARD_InitDAC(void){
    const port_pin_config_t port_DAC_config = {/* Internal pull-up/down resistor is disabled */
                                                    kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    kPORT_LowDriveStrength,
                                                    /* Pin is configured as DAC0_OUT */
                                                    kPORT_MuxAlt0,
                                                    /* Digital input disabled; it is required for analog functions */
                                                    kPORT_InputBufferDisable,
                                                    /* Digital input is not inverted */
                                                    kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    kPORT_UnlockRegister};
    /* PORT4_2 (pin T1) is configured as DAC0_OUT */
    PORT_SetPinConfig(PORT4, 2U, &port_DAC_config);
    /* PORT4_3 (pin U1) is configured as DAC1_OUT */
    PORT_SetPinConfig(PORT4, 3U, &port_DAC_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPWM
 * Description   : Configures pin routing for PWM
 *
 * END ****************************************************************************************************************/
void BOARD_InitPWM(void){
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port2);

    const port_pin_config_t port_PWM_config = {/* Internal pull-up/down resistor is disabled */
                                                      kPORT_PullDisable,
                                                      /* Low internal pull resistor value is selected. */
                                                      kPORT_LowPullResistor,
                                                      /* Fast slew rate is configured */
                                                      kPORT_FastSlewRate,
                                                      /* Passive input filter is disabled */
                                                      kPORT_PassiveFilterDisable,
                                                      /* Open drain output is disabled */
                                                      kPORT_OpenDrainDisable,
                                                      /* Low drive strength is configured */
                                                      kPORT_LowDriveStrength,
                                                      /* Pin is configured as CT0_MAT0 */
                                                      kPORT_MuxAlt4,
                                                      /* Digital input enabled */
                                                      kPORT_InputBufferEnable,
                                                      /* Digital input is not inverted */
                                                      kPORT_InputNormal,
                                                      /* Pin Control Register fields [15:0] are not locked */
                                                      kPORT_UnlockRegister};
    /* PORT2_0 (pin H2) is configured as CT0_MAT0 */
    PORT_SetPinConfig(PORT2, 0U, &port_PWM_config);
    /* PORT2_1 (pin H1) is configured as CT0_MAT0 */
    PORT_SetPinConfig(PORT2, 1U, &port_PWM_config);
    /* PORT2_7 (pin L2) is configured as FLEXIO0_D15 */
    PORT_SetPinConfig(PORT2, 7U, &port_PWM_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
