/*
 * Copyright 2022-2023 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*!
 * @brief Configures pin routing for ADC.
 *
 */
void BOARD_InitADC(void);

/*!
 * @brief Configures pin routing for DAC.
 *
 */
void BOARD_InitDAC(void);

/*!
 * @brief Configures pin routing for UART.
 *
 */
void BOARD_InitUART(void);

/*!
 * @brief Configures pin routing for GPIO.
 *
 */
void BOARD_InitGPIO(void);

/*!
 * @brief Configures pin routing for PWM.
 *
 */
void BOARD_InitPWM(void);

/*!
 * @brief Configures pin routing for CAN.
 *
 */
void BOARD_InitCAN(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
